version: 2.1

jobs:
  build:
    docker:
      - image: cimg/ruby:3.2.2
      - environment:
          POSTGRES_DB: brain_food_test
          POSTGRES_USER: postgres
        image: circleci/postgres:9.5-alpine
      environment:
        PGHOST: 127.0.0.1
        PGPASSWORD: ''
        PGUSER: postgres
        RAILS_ENV: test
    steps:
      - checkout
      - ruby/install-deps
      - run:
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
          name: Wait for DB
      - run:
          command: bundle exec rails db:schema:load --trace
          name: Database setup
      - run: bundle install
      - run: rails db:{drop,create,migrate,seed}
      - run: bundle exec rspec 

workflows:
  version: 2
  build:
    jobs:
      - build
