version: 2.1

jobs:
  build:
    docker:
      - image: cimg/ruby:3.1.4
    steps:
      - checkout
      - run: bundle install
      # - run: rails db:{drop,create,migrate,seed}
      - run: bundle exec rspec 

workflows:
  version: 2
  build:
    jobs:
      - build
